# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YNPageViewController' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YNPageViewController

    #  测试
    pod 'LookinServer','~> 1.0.0', :configurations => ['Debug'],:inhibit_warnings => true

end
